export const CHANGECURRENTROUTE = 'CHANGECURRENTROUTE';
export type CHANGECURRENTROUTE = typeof CHANGECURRENTROUTE;

export const CHANGELOADING = 'CHANGELOADING';
export type CHANGELOADING = typeof CHANGELOADING;